# Generated by Django 6.0.8 on 2026-09-08 19:30

import community.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=50, unique=True, verbose_name='게시판명')),
                ('allow_comment', models.BooleanField(default=True, verbose_name='댓글 허용')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판',
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='유형명')),
            ],
            options={
                'verbose_name': '회원 유형',
                'verbose_name_plural': '회원 유형',
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(db_column='login_id', error_messages={'unique': '이미 사용 중인 아이디입니다.'}, max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='아이디')),
                ('date_joined', models.DateTimeField(db_column='joined_at', default=django.utils.timezone.now, verbose_name='가입일시')),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=100, verbose_name='이메일')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', '숫자만 10자리 또는 11자리로 입력하세요.')], verbose_name='전화번호')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.PROTECT, related_name='members', to='community.usertype', verbose_name='회원 유형')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원',
                'db_table': 'member',
            },
            managers=[
                ('objects', community.models.MemberManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='community.board', verbose_name='게시판')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='community.post', verbose_name='원 질문')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글',
                'db_table': 'post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('stored_path', models.FileField(max_length=500, upload_to='attachments/%Y/%m/', verbose_name='저장 경로')),
                ('file_size', models.BigIntegerField(verbose_name='파일 크기')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='community.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
                'db_table': 'attachment',
                'ordering': ['attachment_id'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post', verbose_name='게시글')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'post_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('일반', '일반'), ('질문', '질문'), ('답변', '답변')], default='일반', max_length=10, verbose_name='권한 구분')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='community.board', verbose_name='게시판')),
                ('user_type', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='community.usertype', verbose_name='회원 유형')),
            ],
            options={
                'verbose_name': '작성 권한',
                'verbose_name_plural': '작성 권한',
                'db_table': 'board_permission',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='내용')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송일시')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽음일시')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='받는 사람')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람')),
            ],
            options={
                'verbose_name': '쪽지',
                'verbose_name_plural': '쪽지',
                'db_table': 'message',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['receiver', '-sent_at'], name='ix_message_receiver')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['board', '-created_at'], name='ix_post_board_created'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['parent'], name='ix_post_parent'),
        ),
        migrations.AddConstraint(
            model_name='boardpermission',
            constraint=models.UniqueConstraint(fields=('board', 'user_type', 'permission_type'), name='uq_board_permission'),
        ),
    ]
