# Generated by Django 6.0.8 on 2026-09-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_deleted',
            field=models.BooleanField(db_default=False, default=False, verbose_name='받는 사람이 삭제'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_deleted',
            field=models.BooleanField(db_default=False, default=False, verbose_name='보낸 사람이 삭제'),
        ),
    ]
