# Generated by Django 6.0.8 on 2026-09-14 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_message_receiver_deleted_message_sender_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_anonymous',
            field=models.BooleanField(db_default=False, default=False, help_text='켜면 글 작성자를 화면에서 가립니다. 댓글 작성자는 그대로 보입니다.', verbose_name='익명 게시판'),
        ),
        migrations.AddField(
            model_name='post',
            name='accepted_answer',
            field=models.OneToOneField(blank=True, help_text="Q&A 질문에만 씁니다. 값이 있으면 '해결됨' 상태입니다.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='community.post', verbose_name='채택된 답변'),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveIntegerField(db_default=0, default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.postcomment', verbose_name='원 댓글'),
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('recruit_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='제목')),
                ('content', models.TextField(verbose_name='소개')),
                ('field', models.CharField(max_length=50, verbose_name='모집 분야')),
                ('headcount', models.PositiveSmallIntegerField(default=1, verbose_name='모집 인원')),
                ('deadline', models.DateField(verbose_name='마감일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('is_closed', models.BooleanField(default=False, verbose_name='모집 마감')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruits', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '팀원 모집',
                'verbose_name_plural': '팀원 모집',
                'db_table': 'recruit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('bookmark_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='저장일시')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='community.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크',
                'db_table': 'bookmark',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('member', 'post'), name='uq_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('쪽지', '쪽지'), ('댓글', '댓글'), ('답변', '답변'), ('모집', '모집')], max_length=10, verbose_name='종류')),
                ('message', models.CharField(max_length=200, verbose_name='문구')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='이동할 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽음일시')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='받는 사람')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receiver', '-created_at'], name='ix_notification_receiver')],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='누른일시')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '추천',
                'verbose_name_plural': '추천',
                'db_table': 'post_like',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('member', 'post'), name='uq_post_like')],
            },
        ),
        migrations.CreateModel(
            name='RecruitApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, verbose_name='지원 메시지')),
                ('status', models.CharField(choices=[('대기', '대기'), ('승인', '승인'), ('거절', '거절')], default='대기', max_length=10, verbose_name='상태')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='지원일시')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='처리일시')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit_applications', to=settings.AUTH_USER_MODEL, verbose_name='지원자')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='community.recruit', verbose_name='모집')),
            ],
            options={
                'verbose_name': '모집 지원',
                'verbose_name_plural': '모집 지원',
                'db_table': 'recruit_application',
                'ordering': ['applied_at'],
                'constraints': [models.UniqueConstraint(fields=('recruit', 'applicant'), name='uq_recruit_application')],
            },
        ),
    ]
